# The Defaults List is a list in an input config that instructs Hydra how to build the output config.
defaults:
  - _self_
  - dataset: uniref50
  - tokenizer: amplify_tokenizer
  - model: 
    - amplify
    - 8M
  - optimizer: adamw
  - scheduler: cosine_decay
  - trainer:
    - base
    - mlm
  - strategy: 
    - constrained

seed: 0

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/hydra

wandb:
  name: null
  project: amplify
  entity: tecchk-cyt-duke-university
  tags: []
  dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/wandb
  mode: online
  log_interval: 100